---
# tasks file for strongswan-svr

- name: Install StrongSwan apt packages
  become: true
  apt:
    update_cache: true
    name: [ strongswan, strongswan-swanctl, strongswan-pki, libstrongswan-standard-plugins, libstrongswan-extra-plugins, libcharon-standard-plugins, libcharon-extra-plugins ]
    state: present

- name: Create ipsec configuration
  become: true
  template:
    src: ipsec.conf.j2
    dest: /etc/ipsec.conf
    owner: root
    group: root
    mode: 0644
  notify: restart strongswan

- name: Create ipsec secrets
  become: true
  template:
    src: ipsec.secrets.j2
    dest: /etc/ipsec.secrets
    owner: root
    group: root
    mode: 0400
  notify: restart strongswan

- name: Grant access to certificate and key files in Apparmor
  become: true
  lineinfile:
    path: /etc/apparmor.d/local/usr.lib.ipsec.charon
    regexp: "{{ item.pattern }}"
    line: "{{ item.line }}"
    state: present
    backup: true
  with_items:
  - { pattern: '/etc/letsencrypt/live/{{ vpn.hostname }}/*', line: '  /etc/letsencrypt/live/{{ vpn.hostname }}/*     r,' }
  - { pattern: '/etc/letsencrypt/archive/{{ vpn.hostname }}/*', line: '  /etc/letsencrypt/archive/{{ vpn.hostname }}/*     r,' }
  notify:
  - restart apparmor
  - restart strongswan

- name: Setup DHCP from given interface
  become: true
  lineinfile:
    path: /etc/strongswan.d/charon/dhcp.conf
    regexp: "{{ item.pattern }}"
    line: "{{ item.line }}"
    state: present
    backup: true
  with_items:
  - { pattern: 'force_server_address=yes', line: '    force_server_address=yes' }
  - { pattern: 'identity_lease=no', line: '    identity_lease=no' }
  - { pattern: 'interface={{ vpn.dhcp.interface }}', line: '    interface={{ vpn.dhcp.interface  }}' }
  - { pattern: 'server={{ vpn.dhcp.broadcast }}', line: '    server={{ vpn.dhcp.broadcast }}' }
  when: vpn.dhcp is defined and vpn.dhcp.interface is defined and vpn.dhcp.broadcast is defined

- name: Restart StrongSwan
  become: true
  service:
    name: strongswan
    state: restarted
