---
# tasks file for strongswan-svr

- name: Install StrongSwan apt packages
  become: true
  apt:
    update_cache: true
    name: [ strongswan, strongswan-swanctl, strongswan-pki, libstrongswan-standard-plugins, libstrongswan-extra-plugins, libcharon-standard-plugins, libcharon-extra-plugins ]
    state: present
