---
# handlers file for strongswan-svr

- name: start strongswan
  become: true
  service:
    name: strongswan
    state: started

- name: restart strongswan
  become: true
  service:
    name: strongswan
    state: restarted

- name: restart apparmor
  become: true
  service:
    name: apparmor
    state: restarted
